_target_: diffusion_policy.workspace.train_diffusion_transformer_hybrid_workspace.TrainDiffusionTransformerHybridWorkspace
n_action_steps: 8
horizon: 10
n_demo: 199
n_eval: 30
seed: 42
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: waypoint_action_${n_action_steps}_horizon_${horizon}_${n_demo}_demo_mul_${task.env_runner.multiplier}_train_diffusion_transformer_hybrid_square_image
  project: diffusion_policy_debug
  resume: false
  tags:
  - train_diffusion_transformer_hybrid
  - square_image
  - default
multi_run:
  run_dir: data/outputs/2022.12.30/18.30.40_train_diffusion_transformer_hybrid_square_image
  wandb_name_base: 2022.12.30-18.30.40_train_diffusion_transformer_hybrid_square_image
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_transformer_hybrid
obs_as_cond: true
optimizer:
  betas:
  - 0.9
  - 0.95
  learning_rate: 0.0001
  obs_encoder_weight_decay: 1.0e-06
  transformer_weight_decay: 0.001
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_transformer_hybrid_image_policy.DiffusionTransformerHybridImagePolicy
  causal_attn: true
  crop_shape:
  - 76
  - 76
  eval_fixed_crop: true
  horizon: ${horizon}
  n_action_steps: ${n_action_steps}
  n_cond_layers: 0
  n_emb: 256
  n_head: 4
  n_layer: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  obs_as_cond: true
  obs_encoder_group_norm: true
  p_drop_attn: 0.3
  p_drop_emb: 0.0
  shape_meta:
    action:
      shape:
      - 10
    obs:
      agentview_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
  time_as_cond: true
shape_meta:
  action:
    shape:
    - 10
  obs:
    agentview_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_eef_pos:
      shape:
      - 3
    robot0_eef_quat:
      shape:
      - 4
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_gripper_qpos:
      shape:
      - 2
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    abs_action: true
    dataset_path: data/robomimic/datasets/square/ph/image_abs.hdf5
    horizon: ${horizon}
    n_obs_steps: 2
    pad_after: ${eval:'${n_action_steps} - 1'}
    pad_before: 1
    rotation_rep: rotation_6d
    seed: ${seed}
    shape_meta:
      action:
        shape:
        - 10
      obs:
        agentview_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
    use_cache: true
    val_ratio: ${eval:'1 - ${n_demo} / 200.0'}
    use_waypoint: true
    constant_waypoint: null
  dataset_path: data/robomimic/datasets/square/ph/image_abs.hdf5
  dataset_type: ph
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
    abs_action: true
    crf: 22
    dataset_path: data/robomimic/datasets/square/ph/image_abs.hdf5
    fps: 10
    max_steps: 200
    n_action_steps: ${n_action_steps}
    n_envs: ${n_eval}
    n_obs_steps: 2
    n_test: 50
    n_test_vis: 0
    n_train: 0
    n_train_vis: 0
    multiplier: 10
    past_action: false
    render_obs_key: agentview_image
    shape_meta:
      action:
        shape:
        - 10
      obs:
        agentview_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: square_image
  shape_meta:
    action:
      shape:
      - 10
    obs:
      agentview_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
  task_name: square
task_name: square_image
training:
  checkpoint_every: 100
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 1000
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8000
  rollout_every: 100
  sample_every: 5
  seed: ${seed}
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1000
  resume: true
val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
